source "https://rubygems.org"

gem "rake"
gem "ruboty-alias"
gem "ruboty-google_image"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-bundler"
gem "ruboty-cron"
gem "ruboty-delay"
gem "ruboty-github"
gem "ruboty-syoboi_calendar"
