source "https://rubygems.org"

gem "rake"
gem "ruboty-alias"
gem "ruboty-google_image"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-bundler"
gem "ruboty-cron"
gem "ruboty-github"
gem "ruboty-syoboi_calendar"
gem "ruboty-exec_command"
gem "ruboty-nullpo"
gem "ruboty-lgtm"
gem "ruboty-hatena_hotentry"